# para habilitar IDaaS (Auth0, Okta, Azure AD, etc.) con OAuth 2.0 / OpenID Connect.

app.security.oauth2.client.enabled=true
app.security.oauth2.resource-server.enabled=true
app.security.oauth2.registration-id=idaas
app.security.oauth2.issuer-uri=https://TU-DOMINIO.auth0.com/
app.security.oauth2.success-redirect=http://localhost:3000/auth/callback

spring.security.oauth2.client.registration.idaas.client-id=TU_CLIENT_ID
spring.security.oauth2.client.registration.idaas.client-secret=TU_CLIENT_SECRET
spring.security.oauth2.client.registration.idaas.scope=openid,profile,email
spring.security.oauth2.client.registration.idaas.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.idaas.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.idaas.issuer-uri=https://TU-DOMINIO.auth0.com/

# Si fuera producción produccion LDAPS (reemplaza el servidor embebido):
# app.security.ldap.enabled=false
# spring.ldap.urls=ldaps://ldap.minimarket.cl:636
# spring.ldap.base=dc=minimarket,dc=cl
